[package]
name = "SERVER"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-files = "0.6"

num_cpus = "1.17.0"
hex = "0.4.3"
hmac = "0.12.1"
sha2 = "0.10.9"
env_logger = "0.11.8"
log = "0.4.28"
awc = "3.8.1"
serde_json = "1.0.145"
